version: '3'
services:
  redis:
    image: "redis:alpine"
    ports: 
      - "6379:6379"
  posts:
    build:
      context: ./posts
      dockerfile: Dockerfile
    environment:
      - NPM_TOKEN=4ea9a67f-ce5f-47f6-8f10-d559fe85f954
    command: ["/usr/src/app/wait-for-it.sh", "redis:6379", "--", "npm", "start"]
    links:
      - "redis:redis"
    ports:
      - "3001:3001"
    depends_on:
      - "redis"
    volumes:
      - ./posts:/usr/src/app
      - /usr/src/app/node_modules
  users:
    build:
      context: ./users
      dockerfile: Dockerfile
    links:
      - "redis:redis"
    ports:
      - "3002:3002"
    environment:
      - NPM_TOKEN=4ea9a67f-ce5f-47f6-8f10-d559fe85f954
    volumes:
      - ./users:/usr/src/app
      - /usr/src/app/node_modules
    command: ["/usr/src/app/wait-for-it.sh", "redis:6379", "--", "npm", "start"]
    depends_on:
      - "redis"